services:
  prometheus:
    image: prom/prometheus:v3.8.1
    container_name: torker_prometheus
    user: "root"
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
    ports:
      - 9114:9090
    networks:
      - home

  node-exporter:
    image: prom/node-exporter:v1.10.2
    container_name: torker_node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro,rslave
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)"
    ports:
      - 9113:9100
    networks:
      - home

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    container_name: torker_cadvisor
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro # Reduced to RO where possible
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9112:8080
    networks:
      - home

  grafana:
    image: grafana/grafana:12.3
    container_name: torker_grafana
    restart: unless-stopped
    env_file:
      - .env
    links:
      - prometheus:prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 9111:3000
    networks:
      - home

  loki:
    image: grafana/loki:3.5.9
    container_name: torker_loki
    user: "root"
    restart: unless-stopped
    volumes:
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 9115:3100
    networks:
      - home

  promtail:
    image: grafana/promtail:3.5.9
    container_name: torker_promtail
    user: "root"
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - promtail-positions:/tmp
      - ./promtail-config.yaml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - home

volumes:
  grafana-data:
  prometheus-data:
  loki-data:
  promtail-positions:

networks:
  home:
    external: true
