services:
  prometheus:
    image: prom/prometheus:v3.8.1
    container_name: torker_prometheus
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    expose:
      - 9090
    ports:
      - 9114:9090
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter
    networks:
      - home

  node-exporter:
    image: prom/node-exporter:v1.10.2
    container_name: torker_node_exporter
    restart: unless-stopped
    expose:
      - 9100
    ports:
      - 9113:9100
    networks:
      - home

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    container_name: torker_cadvisor
    restart: unless-stopped
    privileged: true
    environment:
      - DOCKER_API_VERSION=1.52
    command:
      - "--allowlisted_container_labels=com.docker.swarm.service.name"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/containerd/containerd.sock:/run/containerd/containerd.sock:ro
      - /sys:/sys:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/kmsg:/dev/kmsg:ro
    expose:
      - 8080
    ports:
      - 9112:8080
    networks:
      - home

  grafana:
    image: grafana/grafana:12.3
    container_name: torker_grafana
    restart: unless-stopped
    env_file:
      - .env
    links:
      - prometheus:prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_DISABLE_PASSWORD_RESET=true
      - GF_SMTP_ENABLED=false
    ports:
      - 9111:3000
    networks:
      - home

  loki:
    image: grafana/loki:3.5.9
    container_name: torker_loki
    restart: unless-stopped
    volumes:
      - loki-data:/loki
    ports:
      - 9115:3100
    networks:
      - home

  promtail:
    image: grafana/promtail:3.5.9
    container_name: torker_promtail
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - promtail-positions:/tmp
      - ./promtail-config.yaml:/etc/promtail/config.yml:ro
    networks:
      - home

volumes:
  grafana-data:
  prometheus-data:
  loki-data:
  promtail-positions:

networks:
  home:
    external: true
