name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
      PORT: 2222
      DIR: "~/torker"
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.VPS_PRIVATE_KEY }}

      - name: Prepare environment file from secrets
        run: |
          cat <<'EOF' > .env
          GRAFANA_ADMIN_USER=${{ secrets.GRAFANA_ADMIN_USER }}
          GRAFANA_ADMIN_PASSWORD=${{ secrets.GRAFANA_ADMIN_PASSWORD }}
          EOF

      - name: Deploy
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ env.PORT }} ${{ env.VPS_HOST }} >> ~/.ssh/known_hosts

          echo "--- Syncing files to Homelab ---"
          rsync -avz \
            -e "ssh -p ${{ env.PORT }}" \
            ./ ${{ env.VPS_USER }}@${{ env.VPS_HOST }}:${{ env.DIR }}

          echo "--- Rebuilding Containers ---"
          ssh -p ${{ env.PORT }} ${{ env.VPS_USER }}@${{ env.VPS_HOST }} << EOF
            cd ${{ env.DIR }}
            docker compose down
            docker compose up -d --build
            docker image prune -f
          EOF
